syndesisio/syndesis.io

.gitignore
gulpfile.js
layouts/index.html
package.json
themes/syndesis/layouts/partials/footer.html
themes/syndesis/layouts/partials/header.html
yarn.lock

Add SRI for generated scripts and stylesheets

---

README.md
gulpfile.js
layouts/index.html
themes/syndesis/js/connectingDots.js
themes/syndesis/scss/syndesis.scss

Based on http://codepen.io/erikterwan/pen/VamXGe (MIT license)
Many parameters (including fps) can be tuned in index.html
An example can be seen at https://ro14nd.github.io/syndesis.io/

Added simplified version for particles background, less cpu demanding

---

gulpfile.js
themes/syndesis/layouts/partials/footer.html
themes/syndesis/scss/_footer.scss
themes/syndesis/scss/_home.scss

Fixes #41 
Borrows from jimmidyson/syndesis.io#3

fix(topnav): Add background color to mobile dropdown nav

---

layouts/index.html

fix(home): Fix integration icons arrow color and spacing

---

config.yml

fix: Fix title capitalization

---

content/community/engineering_guidelines.md

This is related to Retro Action Item https://github.com/syndesisio/syndesis-project/issues/54

docs: Add some rule wrt to PRs

---

content/community/contributing.md

This adds few details about development on the backend.
fixes #65

chore(web): Details about development workflow

---

content/quickstart.md

Quickstart - disabled demo_data

---

content/quickstart.md

https://github.com/syndesisio/syndesis/issues/1409

OAuthProxy update - #1409

---

themes/syndesis/layouts/partials/sidenav.html

Fixes syndesisio/syndesis#2788

chore: update issues & help link

---

content/community/contributing.md

Updates links removes unreferenced links and clarifies the Base POM use.

chore: update links and basepom description

---

static/start

Reusing our own dev scripts instead to minimize the chance this break over time.
https://github.com/syndesisio/syndesis/issues/4603

fix for #4603 Quickstart install broke related to Camel-K

---

content/docs/development.md
content/faq.md

There were a couple of useful developments tricks that I wanted to leave it somewhere to be easy to find. I guess the FAQ can be a good place.

#5643 Github labels and #6276 useful answered questions for devs

---

content/docs/cli.md
content/docs/connectors.md
content/docs/development.md
content/faq.md

Adding a full backend development guideline to help during onboarding or new contribution as specified in #5633

#5633 Add connector development guidelines

---

content/docs/connectors.md

Added a description to latest icon usage and TP metadata

chode(doc): icons and tp

---

content/docs/datashapes.md

How to configure a connector datashape

chore(doc): datashapes

---

content/docs/cli.md
content/docs/connectors.md
content/docs/development.md

Enhance docs about developing syndesis and cleaning old stuff,
install nexus repo manager, how to see logs, java agent debug,
enable jaeger backed activity log.

Details more build options, pruning, diagnosis, development

---

content/docs/autodiscovery.md

Use less complex wording and more "to the point" explanations

Improving Auto Discovery docs

---

.gitignore
package.json
postcss.config.js
yarn.lock

resolves some security warnings from [here](https://github.com/syndesisio/syndesis.io/network/alerts)

upgrade deps & update gitignore

---

content/blog/20200407-version-1.9.md

I miss a more extensive list of what are the new features for the news piece. I simply don't remember :)
But I am adding a link to the Github release page, so we can add later more details if we want.

Adding news for 1.9.0 release

---

content/faq.md

Adding a QA about public API location

chore(qa): public api doc

---

content/docs/connectors/datamapper.md
content/docs/connectors/datashapes.md

Moving to website and minor improvements to existing DataMapper docs

Data Mapper section added

---

themes/syndesis/scss/syndesis.scss

With a bit of CSS makes the documentation nicer to see.

chore: nicer css for documentation

---

gulpfile.js

Fixes the race in parallelism by invoking callbacks for parallel and for
manual_render when done, this way we can be sure that all manual
rendering tasks have been finished before proceeding to build the via
Hugo.

fix: gulp parallelism

---

themes/syndesis/scss/_asciidoc.scss

Also fixes (some) lint issues.

refactor: remove unused rules, center content

---

gulpfile.js
themes/syndesis/scss/_asciidoc.scss

Enables the TOC in asciidoctor and implements styling.

chore: implement toc for manual

---

content/quickstart.md

* Add option to install on a remote ocp cluster
* Rewrite the minishift installation to remove the outdated templates section.

Rewrite install instructions

---

content/docs/development_quickstart.md

Adds more information on how to run Syndesis outside of OpenShift.

chore: update development quickstart
