content/quickstart.md
Hopefully this fixes some of the previous issues with re-deploying.
=> fix(quickstart): Use single tenant (restricted) templates to make deployment easier

content/quickstart.md
This PR reflects changes from https://github.com/syndesisio/syndesis-openshift-templates/commit/5fd3d0d5286cce0bf39e19ae7bd1c2456bdbe2d4 and Minishift default route-suffix behaviour.
=> docs: Update domain suffix to nip.io

content/quickstart.md
=> Memory requirements on Windows with Hyper-V are higher

config.yml, content/community/engineering_guidelines.md, content/docs.md, content/docs/cli.md, content/docs/development.md, content/quickstart.md, themes/syndesis/layouts/partials/github-corner.html, themes/syndesis/scss/_asciidoc.scss, themes/syndesis/scss/_footer.scss, themes/syndesis/scss/_sidenav.scss, themes/syndesis/scss/syndesis.scss, themes/syndesis/theme.toml
Some changes:
- Temporary admonition, code block workaround for Markdown, add asciidoc SCSS file for now.
- Remove "Code" from top navigation bar, as this is already linked to from the Octocat at the top, and the footer.
- Octocat `rel="nofollow"` for SEO, open in new tab
- Several typo fixes, broken links, internal relative links not working, CSS/padding fixes
Would like to resolve the issue with the table cell background colors, but this may be a futile effort if we are intending to do major changes to the website in the near future (e.g. switch framework or formatting tool). Also a low priority.
=> Additional changes for Dev Docs

themes/syndesis/layouts/partials/topnav.html, themes/syndesis/scss/_navbar.scss
Here is a little fix to show the logo on Firefox, without an explicit width for the container (or for the logo itself) firefox use the space for the navigation menu on the right
=> Fix invisible logo on firefox

content/docs/cli.md
We need to use the "syndesis install" to  Register CRD and grant permissions.
=> Fixed a typo of syndesis install example

gulpfile.js
By default Hugo would bind to `localhost`/`127.0.0.1`, when developing
the website inside the container and exposing the `1313` port this
becomes a problem as a port bound to `localhost` can't be exposed.
This adds the `--bind 0.0.0.0` so that Hugo's server binds to all
interfaces/ip addresses available. This allows the port to be exposed
when running within a container.
=> chore: bind Hugo server to 0.0.0.0

content/docs/connector-schema.md, content/docs/connectors.md, content/docs/datashapes.md
Seems that the newer versions of Hugo prefer the language for the
highlighter to be specified explicitly for the highlight to function
properly.
This change introduces the defines the language for code blocks and does
light cleanups of the whitespace formatting.
=> refactor: cleanup documentation

content/docs/cli.md, content/docs/development.md
This brings over updates made separately in the Syndesis Developer
Handbook in the main Syndesis repository, updates the documents to
replace outdated information and reformats the docs a bit.
I think the docs still are not 100% up to date, at least this would help
in removing the need for parallel documentation in the Syndesis
Developer Handbook and the confusion about where to edit the docs and
where to point users/contributors for documentation.
=> chore: update docs

themes/syndesis/scss/_sidenav.scss, themes/syndesis/scss/_toc.scss, themes/syndesis/scss/syndesis.scss
This makes sure that the TOC takes up as much space as it needs to to
prevent word wrap (as much as possible), making the TOC a bit
unreadable by tweaking the flex layout to have fixed 214px sidenav,
growable TOC and main content taking up remaining space.
For TOC styling this removes the gray background, use of italic for
headings; and increases the line height to make the menu more legible.
Also adds a gradient as a separator from the content.
=> refactor: flexible layout and TOC styling

static/start
With the releases we now provide a ZIP file containing `tools/bin`
directory within it (syndesis-cli.zip), see[1].
Now this `syndesis-cli.zip` can be downloaded in lieu of downloading the
whole syndesis git repository. By default the latest release is
downloaded. Take note that the releases done by daily releases are
pre-releases, and not deemed stable. Stable releases are point releases
done by explicitly triggering the release build. The latest of these
will be available under the `latest` version.
There's also support for specifying the version via `--tag` parameter to
the `start` script. This way pre-release versions can be tested.
This refactors the script for easier readability, by splinting
functional areas into different functions.
The user experience is improved by providing …
=> feat: improved start script

content/docs/architecture/_index.md, content/docs/cli/_index.md, content/docs/connectors/_index.md, content/docs/contributing/_index.md, content/docs/extensions/_index.md, themes/syndesis/layouts/partials/docs/sidenav.html, themes/syndesis/layouts/partials/sidenav.html, themes/syndesis/scss/_sidenav.scss, yarn.lock
cc @squakez  cc @oscerd 
Team, let me know what you think.. I really have no idea what looks good or makes the most sense. The big darker ones look better than thinner icons with more details.
(minus the big red arrows 😂 )
if you don't like it, look at these and let me know what you prefer:
https://fontawesome.com/icons?d=gallery&m=free
fix #168
=> re #168 add icons for connectors + extensions

content/docs/development_quickstart.md
Aside from typos, there's one notable omission - outside of Kubernetes/OpenShift, the UI won't run, complaining about missing dependencies. Calling `syndesis ui --install --build`, as advised in https://syndesis.io/docs/cli/syndesis/, was enough to bootstrap it.
=> development_quickstart.md: fix a few inaccuracies

.circleci/config.yml
The current setup leads to authentication error when accessing Cloudflare API:
```
{"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}
```
We need to use the bearer token (this is what is generated on the account page), and `POST` method for this API, `DELETE` might work, but it's not documented that way.
=> fix(cloudflare): use bearer token

gulpfile.js
Fixes a typo in the name of the watched file and deletes the require()
cache to reload the processor.
=> fix: asciidoc processor reload

asciidoc-processor.js
This way we can make sure that valid HTML is generated. As docinfo
processor would insert markup in the `<head>` element, so we would hack
and have the closing `</head>` at the end of the document.
This way we can apply our header/footer chrome to the resulting HTML.
=> refactor: use post instead of docinfo-processor

gulpfile.js, themes/syndesis/scss/syndesis.scss
Images should appear now, also narrows the text to 80rem for legibility.
=> fix: copy and style images

gulpfile.js
Images were copied to wrong paths, this should fix it.
We need manual, and all other static resources, in place before we
invoke hugo.
=> fix: gulpfile build order and images path

themes/syndesis/scss/_asciidoc.scss, themes/syndesis/scss/_footer.scss
Places the TOC for Asciidoc content on the right, as it is done for the
markdown content.
=> refactor: TOC for in-page content on the right

themes/syndesis/scss/_docs.scss
When targeting the header via fragment, it's position is below the top
navigation, this adds a margin on the top to move the scroll position
so it's visible below the header.
=> fix: add scroll-margin-top for headings

themes/syndesis/scss/_toc.scss
To help with the responsive layout this sets `flex: 1` instead of
`flex: 0 0 auto`, so the `.toc` is shirnkable/growable rather than
taking up as much space as it would like and thus encroaching on the
main content. Another alternative could be to set the `max-width` to
prevent the `.toc` from taking up too much space. With `flex: 1` browser
decides how to split the width between `#sidebar`, `.main-content` and
`.toc`, whereas with `max-width` we could set the maximum width the
`.toc` would take up.
I ended up deciding to go with `flex: 1`, because I could not decide
what `max-width` would be best.
Fixes #203
=> fix(css): make .toc shirinkable/growable
